# 2. DataFrame 구조 이해

## 1. DataFrame 개념

#### 1.1 DataFrame이란?
- 2차원 레이블이 있는 데이터 구조
- 행(Row)과 열(Column)로 구성된 표 형태
- 각 열은 서로 다른 데이터 타입 가능
- Series의 집합으로 볼 수 있음

#### 1.2 DataFrame의 구조
```
         열1    열2    열3
인덱스0   값1    값2    값3
인덱스1   값4    값5    값6
인덱스2   값7    값8    값9
```

#### 1.3 DataFrame vs Series
- **Series**: 1차원 (단일 컬럼)
- **DataFrame**: 2차원 (여러 컬럼)
- DataFrame의 각 컬럼은 Series 객체

---

## 2. DataFrame 구성 요소

#### 2.1 인덱스(Index)
- 행을 식별하는 레이블
- 기본값: 0부터 시작하는 정수
- 사용자 정의 가능

#### 2.2 컬럼(Columns)
- 열을 식별하는 레이블
- 각 컬럼은 하나의 Series
- 컬럼명은 문자열이 일반적

#### 2.3 값(Values)
- 실제 데이터가 저장되는 부분
- 2차원 NumPy 배열로 저장
- 각 컬럼은 다른 타입 가능

---

## 3. DataFrame 생성 방법

#### 3.1 딕셔너리로 생성

In [ ]:
import pandas as pd

In [ ]:
# 가장 일반적인 방법
data = {
    'name': ['Kim', 'Lee', 'Park'],
    'age': [25, 30, 35],
    'city': ['Seoul', 'Busan', 'Incheon']
}
df = pd.DataFrame(data)

#### 3.2 리스트의 딕셔너리로 생성

In [ ]:
data = [
    {'name': 'Kim', 'age': 25, 'city': 'Seoul'},
    {'name': 'Lee', 'age': 30, 'city': 'Busan'},
    {'name': 'Park', 'age': 35, 'city': 'Incheon'}
]
df = pd.DataFrame(data)

#### 3.3 2차원 리스트로 생성

In [ ]:
data = [
    ['Kim', 25, 'Seoul'],
    ['Lee', 30, 'Busan'],
    ['Park', 35, 'Incheon']
]
df = pd.DataFrame(data, columns=['name', 'age', 'city'])

#### 3.4 Series로 생성

In [ ]:
s1 = pd.Series(['Kim', 'Lee', 'Park'], name='name')
s2 = pd.Series([25, 30, 35], name='age')
df = pd.DataFrame({'name': s1, 'age': s2})

#### 3.5 NumPy 배열로 생성

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])

---

## 4. DataFrame 기본 속성

#### 4.1 구조 확인

In [68]:
data = {
    'city': ['서울', '부산', '인천', '대전'],
    'data1': np.random.randint(100000, 1000000, 4),
    'data2': np.random.randint(500000, 5000000, 4)
}
df = pd.DataFrame(data)

In [69]:
print(df.shape)        # (행 수, 열 수)
print(df.size)         # 전체 요소 개수
print(df.ndim)         # 차원 (항상 2)
print(df.index)        # 인덱스 객체
print(df.columns)      # 컬럼 객체
print(df.values)       # NumPy 배열
print(df.dtypes)       # 각 컬럼의 데이터 타입

(4, 3)
12
2
RangeIndex(start=0, stop=4, step=1)
Index(['city', 'data1', 'data2'], dtype='str')
[['서울' 426140 2273218]
 ['부산' 326660 4695357]
 ['인천' 865463 3928372]
 ['대전' 386736 643098]]
city       str
data1    int32
data2    int32
dtype: object

#### 4.2 데이터 미리보기

In [70]:
df.head()       # 처음 5개 행
df.head(10)     # 처음 10개 행
df.tail()       # 마지막 5개 행
df.tail(3)      # 마지막 3개 행

  city   data1    data2
1   부산  326660  4695357
2   인천  865463  3928372
3   대전  386736   643098

#### 4.3 정보 확인

In [71]:
df.info()       # 전체 정보 (타입, 결측치 등)
df.describe()   # 기술통계 (수치형 컬럼만)

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   city    4 non-null      str
 1   data1   4 non-null      int32
 2   data2   4 non-null      int32
dtypes: int32(2), str(1)
memory usage: 220.0 bytes

               data1         data2
count       4.000000  4.000000e+00
mean   501249.750000  2.885011e+06
std    246230.072469  1.804293e+06
min    326660.000000  6.430980e+05
25%    371717.000000  1.865688e+06
50%    406438.000000  3.100795e+06
75%    535970.750000  4.120118e+06
max    865463.000000  4.695357e+06

---

## 5. 컬럼(열) 접근 및 조작

#### 5.1 단일 컬럼 선택

In [72]:
s1 = pd.Series(['Kim', 'Lee', 'Park'], name='name')
s2 = pd.Series([25, 30, 35], name='age')
df = pd.DataFrame({'name': s1, 'age': s2})

In [73]:
# 두 가지 방법 (결과는 Series)
df['name']      # 딕셔너리 방식 (권장)
df.name         # 속성 방식 (컬럼명이 문자열이고 공백 없을 때)

0     Kim
1     Lee
2    Park
Name: name, dtype: str

#### 5.2 여러 컬럼 선택

In [74]:
# 결과는 DataFrame
df[['name', 'age']]

   name  age
0   Kim   25
1   Lee   30
2  Park   35

#### 5.3 컬럼 추가

In [75]:
# 새로운 컬럼 생성
df['salary'] = [3000, 4000, 5000]

# 기존 컬럼으로부터 계산
df['age_10years_later'] = df['age'] + 10

#### 5.4 컬럼 삭제

In [76]:
# 방법 1: drop 메서드
df.drop('salary', axis=1)           # 원본 유지
df.drop('salary', axis=1, inplace=True)  # 원본 수정

# 방법 2: del 키워드
# del df['salary']

#### 5.5 컬럼 이름 변경

In [ ]:
# 특정 컬럼만 변경
# df.rename(columns={'name': '이름', 'age': '나이'})

# 모든 컬럼 변경
# df.columns = ['이름', '나이', '도시']

---

## 6. 행(Row) 접근 및 조작

#### 6.1 위치 기반 인덱싱: iloc

In [ ]:
df.iloc[0]          # 첫 번째 행 (Series)
df.iloc[0:2]        # 처음 2개 행 (DataFrame)
df.iloc[0, 1]       # 0행 1열 값
df.iloc[0:2, 0:2]   # 0-1행, 0-1열

#### 6.2 레이블 기반 인덱싱: loc

In [ ]:
df.loc[0]           # 인덱스 0인 행
df.loc[0:2]         # 인덱스 0~2 (끝 포함!)
df.loc[0, 'name']   # 0행의 name 컬럼
df.loc[0:2, ['name', 'age']]  # 특정 행과 컬럼

#### 6.3 행 추가

In [81]:
# 새로운 행 추가

new_row = pd.Series({'name': 'Choi', 'age': 40, 'city': 'Daegu'})
# df = df.append(new_row, ignore_index=True)

# 또는 concat 사용
df = pd.concat([df, new_row.to_frame().T], ignore_index=True)

#### 6.4 행 삭제

In [ ]:
# df.drop(0)                    # 인덱스 0 삭제
# df.drop([0, 1])               # 여러 행 삭제
# df.drop(0, inplace=True)      # 원본 수정

---

## 7. Boolean 인덱싱

#### 7.1 단일 조건

In [82]:
# 나이가 30 이상인 행
df[df['age'] >= 30]

# 대구에 사는 사람
df[df['city'] == 'Daegu']

   name age  age_10years_later   city
3  Choi  40                NaN  Daegu

#### 7.2 복합 조건

In [83]:
# AND 조건 (&)
df[(df['age'] >= 25) & (df['age'] <= 35)]

# OR 조건 (|)
df[(df['city'] == 'Seoul') | (df['city'] == 'Busan')]

# NOT 조건 (~)
df[~(df['age'] < 30)]

   name age  age_10years_later   city
1   Lee  30               40.0    NaN
2  Park  35               45.0    NaN
3  Choi  40                NaN  Daegu

#### 7.3 isin() 메서드

In [85]:
# 여러 값 중 하나라도 해당
df[df['city'].isin(['Seoul', 'Daegu'])]

   name age  age_10years_later   city
3  Choi  40                NaN  Daegu

---

## 8. DataFrame 정렬

#### 8.1 값 기준 정렬

In [86]:
# 단일 컬럼 정렬
df.sort_values('age')                    # 오름차순
df.sort_values('age', ascending=False)   # 내림차순

# 여러 컬럼 정렬
df.sort_values(['city', 'age'])
df.sort_values(['city', 'age'], ascending=[True, False])

   name age  age_10years_later   city
3  Choi  40                NaN  Daegu
2  Park  35               45.0    NaN
1   Lee  30               40.0    NaN
0   Kim  25               35.0    NaN

#### 8.2 인덱스 기준 정렬

In [87]:
df.sort_index()

   name age  age_10years_later   city
0   Kim  25               35.0    NaN
1   Lee  30               40.0    NaN
2  Park  35               45.0    NaN
3  Choi  40                NaN  Daegu

---

## 9. DataFrame 통계 함수

#### 9.1 기본 통계

In [90]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])

In [91]:
df.mean()       # 각 컬럼의 평균
df.sum()        # 각 컬럼의 합
df.max()        # 각 컬럼의 최댓값
df.min()        # 각 컬럼의 최솟값
df.std()        # 각 컬럼의 표준편차

A    3.0
B    3.0
C    3.0
dtype: float64

#### 9.2 특정 컬럼 통계

In [94]:
s1 = pd.Series(['Kim', 'Lee', 'Park'], name='name')
s2 = pd.Series([25, 30, 35], name='age')
df = pd.DataFrame({'name': s1, 'age': s2})

In [95]:
df['age'].mean()
df['age'].sum()

np.int64(90)

#### 9.3 describe()

In [96]:
# 수치형 컬럼의 기술통계
df.describe()

# 모든 컬럼 포함 (문자열 등)
df.describe(include='all')

       name   age
count     3   3.0
unique    3   NaN
top     Kim   NaN
freq      1   NaN
mean    NaN  30.0
std     NaN   5.0
min     NaN  25.0
25%     NaN  27.5
50%     NaN  30.0
75%     NaN  32.5
max     NaN  35.0

---

## 10. 결측치 처리

#### 10.1 결측치 확인

In [97]:
df.isnull()         # 결측치면 True
df.isnull().sum()   # 각 컬럼의 결측치 개수
df.notnull()        # 결측치가 아니면 True

   name   age
0  True  True
1  True  True
2  True  True

#### 10.2 결측치 처리

In [99]:
# 결측치가 있는 행 제거
df.dropna()

# 결측치가 있는 열 제거
df.dropna(axis=1)

# 모든 값이 결측치인 행만 제거
df.dropna(how='all')

# 특정 컬럼에 결측치가 있는 행 제거
df.dropna(subset=['age'])

# 결측치 채우기
# df.fillna(0)                    # 0으로 채우기
# df.fillna(df.mean())            # 평균으로 채우기
# df.fillna(method='ffill')       # 앞의 값으로 채우기
# df.fillna(method='bfill')       # 뒤의 값으로 채우기

   name  age
0   Kim   25
1   Lee   30
2  Park   35

---

## 11. 데이터 타입 변환

#### 11.1 타입 확인

In [100]:
df.dtypes
df['age'].dtype

dtype('int64')

#### 11.2 타입 변환

In [103]:
# # 단일 컬럼
# df['age'] = df['age'].astype('float')

# # 여러 컬럼
# df = df.astype({'age': 'int', 'salary': 'float'})

# # 문자열로 변환
# df['age'] = df['age'].astype('str')

---
# 공공데이터 포털 데이터로 실습해보기

https://www.data.go.kr/data/3060079/fileData.do
- 결측치 개수 확인
- 기술통계 (숫자 컬럼만)
- 기술통계 (문자들만)
- info() 사용해보기
- 소속 시장명 (또는 상점가)의 컬럼명을 시장명-상점가로 변경
- 소재지 그리고 취급품목들의 각각의 개수
- 소재지 그리고 취급품목들의 각각의 종류들
- 지류형 가맹 여부가 N인 데이터로 이루어진 데이터프레임 출력하기
- 등록년도 컬럼 삭제하기

In [116]:
filepath = r'20250731.csv'
df = pd.read_csv(filepath)
df.head()

,가맹점명,소속 시장명(또는 상점가),소재지,취급품목,지류형 가맹 여부,디지털형 가맹 여부,등록년도
0,초마맨1981,권율 골목형상점가,경기,짜장면 짬뽕 탕수육,Y,Y,2025
1,못난이 꽈배기,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,꽈배기 도너츠,Y,Y,2025
2,일곡열쇠철물,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,열쇠,Y,Y,2025
3,참새 방앗간,권율 골목형상점가,경기,육전 새우전,Y,Y,2025
4,뿔라헤어컷,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,미용,Y,Y,2025

In [152]:
# 결측치 개수 확인      
df.isnull().sum()

가맹점명               40
소속 시장명(또는 상점가)      0
소재지                 0
취급품목              293
지류형 가맹 여부           0
디지털형 가맹 여부          0
dtype: int64

In [153]:
# 기술통계 (숫자 컬럼만)
df.describe()

          가맹점명 소속 시장명(또는 상점가)     소재지    취급품목 지류형 가맹 여부 디지털형 가맹 여부
count   150501         150541  150541  150248    150541     150541
unique  115898           2651      17   22115         1          2
top         노점          남대문시장      서울      한식         Y          Y
freq      2093            846   24190   11604    150541     134338

In [ ]:
# 기술통계 (문자들만)
df.describe(include='string')

          가맹점명 소속 시장명(또는 상점가)     소재지    취급품목 지류형 가맹 여부 디지털형 가맹 여부
count   150501         150541  150541  150248    150541     150541
unique  115898           2651      17   22115         1          2
top         노점          남대문시장      서울      한식         Y          Y
freq      2093            846   24190   11604    150541     134338

In [119]:
# info() 사용해보기
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150541 entries, 0 to 150540
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   가맹점명            150501 non-null  str
 1   소속 시장명(또는 상점가)  150541 non-null  str
 2   소재지             150541 non-null  str
 3   취급품목            150248 non-null  str
 4   지류형 가맹 여부       150541 non-null  str
 5   디지털형 가맹 여부      150541 non-null  str
 6   등록년도            150541 non-null  int64
dtypes: int64(1), str(6)
memory usage: 16.4 MB

In [130]:
# 소속 시장명 (또는 상점가)의 컬럼명을 시장명-상점가로 변경
df.rename(columns={'소속 시장명(또는 상점가)':'시장명-상점가'})

,가맹점명,시장명-상점가,소재지,취급품목,지류형 가맹 여부,디지털형 가맹 여부,등록년도
0,초마맨1981,권율 골목형상점가,경기,짜장면 짬뽕 탕수육,Y,Y,2025
1,못난이 꽈배기,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,꽈배기 도너츠,Y,Y,2025
2,일곡열쇠철물,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,열쇠,Y,Y,2025
3,참새 방앗간,권율 골목형상점가,경기,육전 새우전,Y,Y,2025
4,뿔라헤어컷,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,미용,Y,Y,2025
...,...,...,...,...,...,...,...
150536,태성마트,단양구경시장(단양인정시장),충북,식잡,Y,Y,2010
150537,동산닭집,단양구경시장(단양인정시장),충북,"일반한식,생닭",Y,Y,2010
150538,파마미용실,단양구경시장(단양인정시장),충북,일반미용업,Y,Y,2010
150539,두메하누,단양구경시장(단양인정시장),충북,한식점업,Y,Y,2010
150540,단양보리밥,단양구경시장(단양인정시장),충북,분식,Y,Y,2010

In [132]:
# 소재지 그리고 취급품목들의 각각의 개수
df[['소재지', '취급품목']].nunique()

소재지        17
취급품목    22115
dtype: int64

In [145]:
# 소재지 그리고 취급품목들의 각각의 종류들
df['소재지'].unique()
df['취급품목'].unique()

<ArrowStringArray>
['짜장면 짬뽕 탕수육',    '꽈배기 도너츠',         '열쇠',     '육전 새우전',         '미용',
         '음료',       '채소 등',       '꼬치구이',      '발성 교정',        '육개장',
 ...
      '국기,휘장',      '두부및묵류',   '지물,커텐,카펫',   '생활용품잡화담배',       '의류정장',
     '카펫커튼벽지',     '침구류,잡화',      '생닭.계란',    '한약재,건강즙',    '일반한식,생닭']
Length: 22116, dtype: str

In [148]:
# 지류형 가맹 여부가 N인 데이터로 이루어진 데이터프레임 출력하기
df[df['지류형 가맹 여부'] == 'N']

Empty DataFrame
Columns: [가맹점명, 소속 시장명(또는 상점가), 소재지, 취급품목, 지류형 가맹 여부, 디지털형 가맹 여부, 등록년도]
Index: []

In [149]:
# 등록년도 컬럼 삭제하기
df.drop('등록년도', axis=1)

,가맹점명,소속 시장명(또는 상점가),소재지,취급품목,지류형 가맹 여부,디지털형 가맹 여부
0,초마맨1981,권율 골목형상점가,경기,짜장면 짬뽕 탕수육,Y,Y
1,못난이 꽈배기,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,꽈배기 도너츠,Y,Y
2,일곡열쇠철물,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,열쇠,Y,Y
3,참새 방앗간,권율 골목형상점가,경기,육전 새우전,Y,Y
4,뿔라헤어컷,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,미용,Y,Y
...,...,...,...,...,...,...
150536,태성마트,단양구경시장(단양인정시장),충북,식잡,Y,Y
150537,동산닭집,단양구경시장(단양인정시장),충북,"일반한식,생닭",Y,Y
150538,파마미용실,단양구경시장(단양인정시장),충북,일반미용업,Y,Y
150539,두메하누,단양구경시장(단양인정시장),충북,한식점업,Y,Y
150540,단양보리밥,단양구경시장(단양인정시장),충북,분식,Y,Y

In [150]:
# 등록년도 컬럼 삭제해서 원본을 변경하기
df.drop('등록년도', axis=1, inplace=True)

---

## 12. 실습 예제

#### 예제 1: 학생 성적 데이터
- 여러 과목의 성적을 DataFrame으로 생성
- 총점, 평균 계산
- 특정 기준 이상 학생 필터링

#### 예제 2: 직원 정보 관리
- 이름, 나이, 부서, 급여 정보를 DataFrame으로 생성
- 부서별 평균 급여 계산
- 조건에 맞는 직원 검색

#### 예제 3: 매출 데이터 분석
- 제품별, 월별 매출 데이터 생성
- 결측치 처리
- 정렬 및 통계 분석

In [63]:
# [예제 1] 학생 성적 데이터

In [64]:
# [예제 2] 직원 정보 관리

In [66]:
# [예제 3] 매출 데이터 분석

---

## 13. 주요 개념 정리

1. **DataFrame은 행과 열로 구성된 2차원 데이터 구조**
2. **각 컬럼은 Series 객체이며 다른 타입 가능**
3. **loc (레이블), iloc (위치) 로 행/열 접근**
4. **Boolean 인덱싱으로 조건부 필터링**
5. **결측치를 효과적으로 처리하는 다양한 메서드 제공**

---

## 14. 연습 문제

1. 5명의 학생에 대한 3과목 성적 DataFrame 만들고 분석하기
2. 제품 정보 DataFrame에서 특정 가격 범위 필터링하기
3. 결측치가 있는 직원 데이터를 적절히 처리하기
4. 여러 조건을 조합하여 복잡한 필터링 수행하기